# Скопировать на сервер как /opt/labs/numerical_labs/lab2/.streamlit/config.toml

[server]
headless = true
address = "127.0.0.1"
port = 8502
enableCORS = false
enableXsrfProtection = true
baseUrlPath = "lab2"
fileWatcherType = "none"
